# Generated by Django 3.2.9 on 2022-01-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0002_chatmessage_user'),
        ('hotel', '0002_auto_20211214_1724'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0003_tokenproxy'),
        ('guardian', '0002_generic_permissions_index'),
        ('myapp', '0008_comment'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomJWTUser',
        ),
    ]
