# Generated by Django 3.2.9 on 2022-01-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_comment'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='comment',
            order_with_respect_to='book',
        ),
    ]
