# Generated by Django 3.2.9 on 2022-01-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_comment_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='my_custom_like',
            field=models.IntegerField(default=0),
        ),
    ]
