# Generated by Django 3.2.9 on 2022-01-20 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_comment_my_custom_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='new_like',
            field=models.ManyToManyField(related_name='test_name_comment', through='myapp.CommentBookLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
