# Generated by Django 3.2.9 on 2022-01-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20211214_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderroom',
            options={'get_latest_by': 'date', 'verbose_name': 'бронь', 'verbose_name_plural': 'брони'},
        ),
    ]
