name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install virtualenv
        python -m venv venv
        source venv/bin/activate
        pip install poetry
        poetry update
    - name: Run Tests
      run: |
        source venv/bin/activate
        python manage.py test
