name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    env:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: {{env.POSTGRES_PASSWORD}}
          POSTGRES_USER: {{env.POSTGRES_USER}}
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
        export PATH=$PATH:$HOME/.poetry/bin
        poetry update
    - name: Run Tests
      run: |
        export PATH=$PATH:$HOME/.poetry/bin
        poetry run python manage.py test
