name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
#      postgres:
#        image: postgres
#        env:
#          POSTGRES_PASSWORD: postgres
#        ports:
#          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        export PATH=$PATH:$HOME/.poetry/bin
        ls /opt/hostedtoolcache/Python/3.9.9/x64
        poetry env use /opt/hostedtoolcache/Python/3.9.9/x64
        poetry update
    - name: Run Tests
      run: |
        source /home/runner/.cache/pypoetry/virtualenvs/books-shop-ssCurqa0-py3.9/bin/activate
        python manage.py test
